version: 2

updates:

- package-ecosystem: "nuget"
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 50
  assignees:
    - "guibranco"
  reviewers:
    - "guibranco"
  labels:
    - "nuget"
    - "packages"
    - ".NET"
    - "dependencies"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 50
  assignees:
    - "guibranco"
  reviewers:
    - "guibranco"
  labels:
    - "github-actions"
    - "dependencies"