name: Linter check

on:
  workflow_dispatch:
  pull_request:

jobs:
  linter-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: CSharpier Linter
        uses: guibranco/github-csharpier-linter-action@a0c6d374c050fa681213e55223296909944f1e23 # v1.0.27
